### ISSUE TITLE
filename spelling mistake

### ISSUE THREAD

**Issue by timredfern** [elliotwoods/ofxGraphicAssets#1]
ofxAssets.h is now called ofxGraphicAsssets.h

**Comment by elliotwoods** [comment]
Hey! Can I suggest you look into the other addon 'ofxAssets'
https://github.com/elliotwoods/ofxAssets

That replaces this addon entirely and is the one I'm using / continuing to develop

**Comment by timredfern** [comment]
Ah! My bad.The confusion arose because ofxGraphicAssets is also on the ofxAddons page, wonder would it make sense to remove that?

**Comment by elliotwoods** [comment]
It's harder to edit there (I can't login and the admins are busy people). I'll change the readme here
